#!/bin/env bash

readonly TOOLS_PATH=../tools
readonly TOOLS_CONFIG_PATH=./config/

. ${TOOLS_PATH}

function test_pop_should_put_first_item_in_var() {
    local -a my_array=(apples bananas cherries)
    local popped_item

    pop_into_from_array popped_item my_array

    # Test $popped_item is now what we expect
    assert_var_equals popped_item "apples"
}

function test_pop_should_remove_first_item_from_array() {
    local -a my_array=(apples bananas cherries)
    local popped_item

    local -a expected_final_my_array=(bananas cherries)

    pop_into_from_array popped_item my_array

    # Test $my_array after pop
    if ! [[ "${my_array[@]}" = "${expected_final_my_array[@]}" ]]; then
        err_msg \
            "\$my_array should contain (${expected_final_my_array[@]}), "\
            "contained: (${my_array[@]})"
        return ${FAILURE}
    fi

    # If we reach here, all asserts passed
    return ${SUCCESS}
}

function main() {
    local -i total_tests=2
    local -i tests_failed_count=0

    run_test test_pop_should_put_first_item_in_var tests_failed_count
    run_test test_pop_should_remove_first_item_from_array tests_failed_count

    give_test_summary ${tests_failed_count} ${total_tests}
}

main
