#!/bin/bash
#
# Functions for installing and managing MongoDB from mongodb.org
#

mongodb__install() {
    if using_yum; then
        mongodb__install__yum
        return $?
    elif using_apt; then
        # add package source
        with_sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
        sudo add-apt-repository 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'

        # install
        install_packages mongodb-org
        return $?
    fi

    err_msg Not supported on this platform yet
    return ${FAILURE}
}

mongodb__install__yum() {
    # Add the MongoDB yum repo
    #
    # This uses a Heredoc. See:
    #     http://mywiki.wooledge.org/BashGuide/InputAndOutput#Heredocs_And_Herestrings
    #
    with_sudo "cat > /etc/yum.repos.d/mongodb.repo" <<END_DOC
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1

END_DOC

    # Now update package lists to get metadata from the new repo
    update_package_lists

    install_packages mongodb-org
}
