#!/bin/bash

basket__include package_management/yum

apache__install_2_2() {
    if using_yum; then
        if yum__package_exists 'httpd-2.2.*'; then
            local apache="httpd"
        elif yum__package_exists 'httpd22'; then
            local apache="httpd22"
        else
            err_msg "Couldn't confidently determine which package provides PHP 5.3"
            return ${FAILURE}
        fi

        install_packages "${apache}"
        return ${SUCCESS}
    else
        # XXX TODO non-yum installs still needs work
        err_msg "Apache 2.2 install on non-yum systems not supported yet"
        return ${FAILURE}
    fi
}

apache__install_2_4() {
    if using_apt; then
        install_packages "apache2"
    elif use_yum; then
        # blah blah blah
    else
        err_msg "Installing Apache 2.4 through Basket is unsupported on your OS, use install_packages"
        return ${FAILURE}
    fi
}

apache__configure() {
    local config_name=$1

    echo Configuring apache for ${config_name}...

    local config_path="$(config_file apache/${config_name}.conf)"
    local dest_config_path="/etc/apache2/sites-enabled/${nginx_config_name}"

    if ! with_sudo "[[ -f \"${config_path}\" ]]"; then
        err_msg "Could not find Apache config file at ${config_path}"
        return ${FAILURE}
    fi

    # TODO: Refactor to use `apache2 -V` to find config folder
    with_sudo "\
        rm -f /etc/apache2/sites-enabled/000-default.conf \
            && cp \"${config_path}\" \"${dest_config_path}\""

    with_sudo "a2enmod rewrite"

    # restart after loading everything
    if using_yum; then
        with_sudo "a2enmod php5"
        with_sudo "service httpd restart"
    elif is_platform "Ubuntu"; then
        # set up PHP5 where needed
        with_sudo "apt-get install libapache2-mod-php5"
        with_sudo "a2enmod php5"
        with_sudo "service apache2 restart"
    else
        err_msg "Can't restart Apache; Basket doesn't support this OS yet"
        return ${FAILURE}
    fi

    echo Done configuring Apache for ${config_name}.
}
