#!/bin/bash

apache__configure() {
    local config_name=$1

    echo Configuring apache for ${config_name}...

    local config_path="$(config_file apache/${config_name}.conf)"
    local dest_config_path="/etc/apache2/sites-enabled/${nginx_config_name}"

    if ! with_sudo "[[ -f \"${config_path}\" ]]"; then
        err_msg "Could not find apache config file at ${config_path}"
        return ${FAILURE}
    fi

    with_sudo "\
        rm -f /etc/apache2/sites-enabled/000-default.conf \
            && cp \"${config_path}\" \"${dest_config_path}\" \
            && service apache2 restart
    "
    
    with_sudo "apt-get install libapache2-mod-php5"
    with_sudo "a2enmod php5"
    with_sudo "a2enmod rewrite"

    echo Done configuring nginx for ${config_name}.
}
