#!/bin/bash

ssh__disable_root_login() {
	with_sudo "find_replace_in_file \"^PermitRootLogin\" \"#PermitRootLogin\" /etc/ssh/sshd_config"
	with_sudo "echo \"PermitRootLogin no\" >> /etc/ssh/sshd_config"

	with_sudo service sshd restart
}

ssh__disable_password_login() {
	with_sudo "find_replace_in_file \"^PasswordAuthentication\" \"#PasswordAuthentication\" /etc/ssh/sshd_config"
	with_sudo "echo \"PasswordAuthentication no\" >> /etc/ssh/sshd_config"

	with_sudo service sshd restart
}
