#!/bin/bash

# This can be used with package name/version patterns, eg "php-5.3.*"
yum__package_exists() {
    local package_name_or_pattern=$1

    # Joyously, yum list/info don't respect --quiet
    yum list "${package_name_or_pattern}" 1>/dev/null 2>/dev/null
}
