#!/bin/bash

nodejs__install() {
    echo Installing node.js...

    if is_package_installed nodejs && which node; then
        echo node.js is already installed.
        return 0
    fi

    install_packages nodejs

    # Some scripts expect the node.js binary to just be called "node", and on
    # some distros (eg Ubuntu) it's called "nodejs".
    # This adds a symlink so "node" still works.
    if ! which node; then
        # TODO Make this handle `which nodejs` being a symlink itself
        ln -s `which nodejs` /usr/bin/node
    fi
    echo Done installing node.js.
}

nodejs__install_npm() {
    # TODO This could possibly be more robust
    echo "Installing npm (and node.js if needed)..."
    nodejs__install

    if ! is_package_installed npm; then
        echo npm is already installed.
        return 0
    fi

    install_packages npm
    echo Done installing npm.
}


#
# Bower package management
#
nodejs__bower_install_packages() {
    local package_names=$@

    echo Installing with bower: ${package_names}
    bower install --config.interactive=false ${package_names}
}
