#!/bin/bash

php__install() {
    echo Installing PHP...
    install_packages \
        php5 php5-cli php5-readline php5-mysql php5-sqlite php5-fpm \
        php5-imagick php5-xdebug php5-curl php5-mcrypt \
        php php-cli php-readline php-mysql php-sqlite php-fpm \
        php-imagick php-xdebug php-curl php-mcrypt
    echo Done installing PHP.

    # :TODO: some distros (Centos 6, possibly others) do not have yum packages for php's imagick, xdebug and sqlite libraries.
    # Will have to detect this and install PECL to load those in.
}

php__install_composer() {
    echo Installing composer...

    if is_file ${COMPOSER_INSTALL_PATH}; then
        echo composer is already installed.
        return 0
    fi

    with_sudo curl --silent --output ${COMPOSER_INSTALL_PATH} ${COMPOSER_INSTALLER_URL}
    with_sudo chmod +x ${COMPOSER_INSTALL_PATH}
    echo Done installing composer.
}

