#!/bin/bash

basket__include package_management/yum

php__install() {
    echo Installing PHP...

    # TODO: This really needs to be more robust
    if using_yum; then
        install_packages \
            php php-cli php-readline php-mysql php-sqlite php-fpm \
            php-imagick php-xdebug php-curl php-mcrypt php-xml
    elif using_apt; then
        install_packages \
            php5 php5-cli php5-readline php5-mysql php5-sqlite php5-fpm \
            php5-imagick php5-xdebug php5-curl php5-mcrypt php5-xml
    else
        err_msg "Currently this only supports Ubuntu/Debian and Amazon Linux"
        return ${FAILURE}
    fi

    echo Done installing PHP.
    # :TODO: some distros (Centos 6, possibly others) do not have yum packages for php's imagick, xdebug and sqlite libraries.
    # Will have to detect this and install PECL to load those in.
}

php__install_5_3() {
    echo Installing PHP 5.3...

    if using_yum; then
        if yum__package_exists 'php-5.3.*'; then
            local php53="php"
        elif yum__package_exists 'php53'; then
            local php53="php53"
        else
            err_msg "Couldn't confidently determine which package provides PHP 5.3"
            return ${FAILURE}
        fi

        # Thus far, tested on Amazon Linux
        install_packages \
            ${php53} ${php53}-cli ${php53}-readline ${php53}-mysql \
            ${php53}-sqlite ${php53}-fpm ${php53}-imagick \
            ${php53}-xdebug ${php53}-curl ${php53}-mcrypt ${php53}-xml
    else
        # XXX TODO non-yum installs still needs work
        err_msg "PHP 5.3 install on non-yum systems not supported yet"
        return ${FAILURE}
    fi

    echo Done installing PHP 5.3
}

php__install_5_5() {
    echo Installing PHP 5.5...

    if using_yum; then
        if yum__package_exists 'php-5.5.*'; then
            local php55="php"
        elif yum__package_exists 'php55'; then
            local php55="php55"
        else
            err_msg "Couldn't confidently determine which package provides PHP 5.5"
            return ${FAILURE}
        fi

        # Thus far, tested on Amazon Linux
        install_packages \
            ${php55} ${php55}-cli ${php55}-readline ${php55}-mysqlnd \
            ${php55}-sqlite ${php55}-fpm ${php55}-imagick \
            ${php55}-xdebug ${php55}-curl ${php55}-mcrypt ${php55}-xml
    else
        # XXX TODO non-yum installs still needs work
        err_msg "PHP 5.5 install on non-yum systems not supported yet"
        return ${FAILURE}
    fi

    echo Done installing PHP 5.5
}

php__install_composer() {
    echo Installing composer...

    if is_file ${COMPOSER_INSTALL_PATH}; then
        echo composer is already installed.
        return 0
    fi

    with_sudo curl --silent --output ${COMPOSER_INSTALL_PATH} ${COMPOSER_INSTALLER_URL}
    with_sudo chmod +x ${COMPOSER_INSTALL_PATH}
    echo Done installing composer.
}

